apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
  namespace: infra-data
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
      - name: kong-migration
        image: kong:0.13.1-alpine
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_PG_PASSWORD
            value: Kongpass123
          - name: KONG_PG_HOST
            value: ext-postgres.infra-data.svc.cluster.local
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: Never
