apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra-data
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  namespace: infra-data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.5
        command:
          - sleep
          - "3600"



