
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-rc3
  namespace: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
        release: rc3
    spec:
      containers:
      - name: echo
        image: bettercode/echoserver:1.8m 
        ports:
        - containerPort: 8080
        env:
          - name: ECHO_MSG
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
